FROM openjdk:12-alpine

COPY server/build/libs/pickaxe-server.jar /home/pickaxe/
COPY server/build/deps/* /home/pickaxe/
COPY client/build/ /home/pickaxe/html/pickaxe

WORKDIR /home/pickaxe/
CMD java -cp "*" ServerKt
