FROM openjdk:12-alpine

COPY server/build/libs/pickaxe-server.jar /home/pickaxe/pickaxe-server.jar
COPY client/build/ /home/pickaxe/html/pickaxe

WORKDIR /home/pickaxe/
CMD java -jar pickaxe-server.jar
