FROM openjdk:12-alpine

COPY server/build/libs/pickaxe-server-0.1.jar /home/pickaxe/pickaxe-server-0.1.jar
COPY client/build/ /home/pickaxe/html/pickaxe

WORKDIR /home/pickaxe/
CMD java -jar pickaxe-server-0.1.jar
